// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: banyan_go_types.proto

package pa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HardClause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lits []int32 `protobuf:"varint,2,rep,packed,name=lits,proto3" json:"lits,omitempty"`
}

func (x *HardClause) Reset() {
	*x = HardClause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banyan_go_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardClause) ProtoMessage() {}

func (x *HardClause) ProtoReflect() protoreflect.Message {
	mi := &file_banyan_go_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardClause.ProtoReflect.Descriptor instead.
func (*HardClause) Descriptor() ([]byte, []int) {
	return file_banyan_go_types_proto_rawDescGZIP(), []int{0}
}

func (x *HardClause) GetLits() []int32 {
	if x != nil {
		return x.Lits
	}
	return nil
}

type SoftClause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight int32   `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Lits   []int32 `protobuf:"varint,2,rep,packed,name=lits,proto3" json:"lits,omitempty"`
}

func (x *SoftClause) Reset() {
	*x = SoftClause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banyan_go_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoftClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftClause) ProtoMessage() {}

func (x *SoftClause) ProtoReflect() protoreflect.Message {
	mi := &file_banyan_go_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftClause.ProtoReflect.Descriptor instead.
func (*SoftClause) Descriptor() ([]byte, []int) {
	return file_banyan_go_types_proto_rawDescGZIP(), []int{1}
}

func (x *SoftClause) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SoftClause) GetLits() []int32 {
	if x != nil {
		return x.Lits
	}
	return nil
}

type Problem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId   int32         `protobuf:"varint,1,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	NumVars     int32         `protobuf:"varint,2,opt,name=numVars,proto3" json:"numVars,omitempty"`
	NumClauses  int32         `protobuf:"varint,3,opt,name=numClauses,proto3" json:"numClauses,omitempty"`
	TopWeight   int32         `protobuf:"varint,4,opt,name=topWeight,proto3" json:"topWeight,omitempty"`
	HardClauses []*HardClause `protobuf:"bytes,5,rep,name=hardClauses,proto3" json:"hardClauses,omitempty"`
	SoftClauses []*SoftClause `protobuf:"bytes,6,rep,name=softClauses,proto3" json:"softClauses,omitempty"`
}

func (x *Problem) Reset() {
	*x = Problem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banyan_go_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_banyan_go_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_banyan_go_types_proto_rawDescGZIP(), []int{2}
}

func (x *Problem) GetClusterId() int32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *Problem) GetNumVars() int32 {
	if x != nil {
		return x.NumVars
	}
	return 0
}

func (x *Problem) GetNumClauses() int32 {
	if x != nil {
		return x.NumClauses
	}
	return 0
}

func (x *Problem) GetTopWeight() int32 {
	if x != nil {
		return x.TopWeight
	}
	return 0
}

func (x *Problem) GetHardClauses() []*HardClause {
	if x != nil {
		return x.HardClauses
	}
	return nil
}

func (x *Problem) GetSoftClauses() []*SoftClause {
	if x != nil {
		return x.SoftClauses
	}
	return nil
}

type Problems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Problems []*Problem `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
}

func (x *Problems) Reset() {
	*x = Problems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banyan_go_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Problems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problems) ProtoMessage() {}

func (x *Problems) ProtoReflect() protoreflect.Message {
	mi := &file_banyan_go_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problems.ProtoReflect.Descriptor instead.
func (*Problems) Descriptor() ([]byte, []int) {
	return file_banyan_go_types_proto_rawDescGZIP(), []int{3}
}

func (x *Problems) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Lits   []int32 `protobuf:"varint,2,rep,packed,name=lits,proto3" json:"lits,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banyan_go_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_banyan_go_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_banyan_go_types_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Result) GetLits() []int32 {
	if x != nil {
		return x.Lits
	}
	return nil
}

type Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterRst map[int32]*Result `protobuf:"bytes,1,rep,name=clusterRst,proto3" json:"clusterRst,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Results) Reset() {
	*x = Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banyan_go_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_banyan_go_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_banyan_go_types_proto_rawDescGZIP(), []int{5}
}

func (x *Results) GetClusterRst() map[int32]*Result {
	if x != nil {
		return x.ClusterRst
	}
	return nil
}

var File_banyan_go_types_proto protoreflect.FileDescriptor

var file_banyan_go_types_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x6e, 0x79, 0x61, 0x6e, 0x5f, 0x67, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x61, 0x6e, 0x79, 0x61, 0x6e, 0x22,
	0x20, 0x0a, 0x0a, 0x48, 0x61, 0x72, 0x64, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x74,
	0x73, 0x22, 0x38, 0x0a, 0x0a, 0x53, 0x6f, 0x66, 0x74, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x74, 0x73, 0x22, 0xeb, 0x01, 0x0a, 0x07,
	0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x72, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x34, 0x0a,
	0x0b, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x6e, 0x79, 0x61, 0x6e, 0x2e, 0x48, 0x61, 0x72, 0x64,
	0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0b, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6c, 0x61, 0x75,
	0x73, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x6f, 0x66, 0x74, 0x43, 0x6c, 0x61, 0x75, 0x73,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x6e, 0x79, 0x61,
	0x6e, 0x2e, 0x53, 0x6f, 0x66, 0x74, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0b, 0x73, 0x6f,
	0x66, 0x74, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x6e, 0x79, 0x61, 0x6e,
	0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x73, 0x22, 0x34, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x74, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x61, 0x6e, 0x79, 0x61,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x73, 0x74, 0x1a, 0x4d, 0x0a, 0x0f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x79,
	0x61, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x62, 0x61, 0x6e, 0x79, 0x61, 0x6e, 0x2f, 0x70,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_banyan_go_types_proto_rawDescOnce sync.Once
	file_banyan_go_types_proto_rawDescData = file_banyan_go_types_proto_rawDesc
)

func file_banyan_go_types_proto_rawDescGZIP() []byte {
	file_banyan_go_types_proto_rawDescOnce.Do(func() {
		file_banyan_go_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_banyan_go_types_proto_rawDescData)
	})
	return file_banyan_go_types_proto_rawDescData
}

var file_banyan_go_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_banyan_go_types_proto_goTypes = []interface{}{
	(*HardClause)(nil), // 0: banyan.HardClause
	(*SoftClause)(nil), // 1: banyan.SoftClause
	(*Problem)(nil),    // 2: banyan.Problem
	(*Problems)(nil),   // 3: banyan.Problems
	(*Result)(nil),     // 4: banyan.Result
	(*Results)(nil),    // 5: banyan.Results
	nil,                // 6: banyan.Results.ClusterRstEntry
}
var file_banyan_go_types_proto_depIdxs = []int32{
	0, // 0: banyan.Problem.hardClauses:type_name -> banyan.HardClause
	1, // 1: banyan.Problem.softClauses:type_name -> banyan.SoftClause
	2, // 2: banyan.Problems.problems:type_name -> banyan.Problem
	6, // 3: banyan.Results.clusterRst:type_name -> banyan.Results.ClusterRstEntry
	4, // 4: banyan.Results.ClusterRstEntry.value:type_name -> banyan.Result
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_banyan_go_types_proto_init() }
func file_banyan_go_types_proto_init() {
	if File_banyan_go_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_banyan_go_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardClause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banyan_go_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoftClause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banyan_go_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Problem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banyan_go_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Problems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banyan_go_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banyan_go_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_banyan_go_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_banyan_go_types_proto_goTypes,
		DependencyIndexes: file_banyan_go_types_proto_depIdxs,
		MessageInfos:      file_banyan_go_types_proto_msgTypes,
	}.Build()
	File_banyan_go_types_proto = out.File
	file_banyan_go_types_proto_rawDesc = nil
	file_banyan_go_types_proto_goTypes = nil
	file_banyan_go_types_proto_depIdxs = nil
}
